### ISSUE TITLE
Error: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by it-git-k** [Prudhvi-pln/udb#54]
Any idea why getting this when trying to download series? Series to download is: "Chang Le Qu - Melody of Golden Age"

Fetching Episodes & Available Resolutions:
Failed to extract download links for episode: 1. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 2. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 3. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 4. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 5. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 6. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 7. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 8. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 9. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 10. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 11. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 12. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 13. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 14. Error: 'NoneType' object has no attribute 'split'
Failed to extract download links for episode: 15. Error: 'NoneType' object has no attribute 'split'
Failed with code: 429
Failed with code: 429
Failed with code: 429
Failed with code: 429
Failed with code: 429
Failed with code: 429
Failed with code: 429
Failed with code: 429
Failed with code: 429
Failed with code: 429
Failed with code: 429
Failed with code: 429

**Comment by it-git-k** [comment]
It works on ffmpeg 7.7.1, but I had to install Ubuntu 25.04 to get that.
